print('Hej!')
print("Jestem Python!")
print("Jak się nazywasz?")
imie = input()
# print('Miło mi Cię poznać', imie, '. Jak się dziś czujesz?')
print(f'Miło mi Cię poznać {imie}. W którym roku się urodziłeś?')
rok_urodzenia = input()
wiek = 2023 - int(rok_urodzenia)
print(f'Wow, masz już {wiek} lat.')
